#include <stdlib.h>
#include "dace_model.h"

int main(int argc, char** argv) {
  float ONNX_100 = 42;
  float ONNX_109 = 42;
  float ONNX_112 = 42;
  float ONNX_115 = 42;
  float ONNX_128 = 42;
  float ONNX_145 = 42;
  float ONNX_148 = 42;
  long long ONNX_27 = 42;
  long long ONNX_30 = 42;
  long long ONNX_42 = 42;
  long long ONNX_45 = 42;
  long long ONNX_56 = 42;
  long long ONNX_59 = 42;
  float ONNX_72 = 42;
  long long ONNX_78 = 42;
  long long ONNX_81 = 42;
  long long ONNX___tmp10 = 42;
  long long ONNX___tmp11 = 42;
  long long ONNX___tmp12 = 42;
  long long ONNX___tmp13 = 42;
  long long ONNX___tmp14 = 42;
  long long ONNX___tmp15 = 42;
  long long ONNX___tmp8 = 42;
  long long ONNX___tmp9 = 42;
  float * __restrict__ ONNX_133 = (float*) calloc(3145728, sizeof(float));
  float * __restrict__ ONNX_134 = (float*) calloc(589824, sizeof(float));
  float * __restrict__ ONNX_135 = (float*) calloc(589824, sizeof(float));
  float * __restrict__ ONNX_136 = (float*) calloc(589824, sizeof(float));
  long long * __restrict__ ONNX_137 = (long long*) calloc(1, sizeof(long long));
  long long * __restrict__ ONNX_138 = (long long*) calloc(1, sizeof(long long));
  long long * __restrict__ ONNX_139 = (long long*) calloc(1, sizeof(long long));
  long long * __restrict__ ONNX_140 = (long long*) calloc(1, sizeof(long long));
  long long * __restrict__ ONNX_141 = (long long*) calloc(1, sizeof(long long));
  long long * __restrict__ ONNX_142 = (long long*) calloc(1, sizeof(long long));
  long long * __restrict__ ONNX_143 = (long long*) calloc(1, sizeof(long long));
  float * __restrict__ ONNX_144 = (float*) calloc(589824, sizeof(float));
  float * __restrict__ ONNX_146 = (float*) calloc(2359296, sizeof(float));
  float * __restrict__ ONNX_147 = (float*) calloc(2359296, sizeof(float));
  long long * __restrict__ ONNX___tmp0 = (long long*) calloc(3, sizeof(long long));
  long long * __restrict__ ONNX___tmp1 = (long long*) calloc(3, sizeof(long long));
  long long * __restrict__ ONNX___tmp16 = (long long*) calloc(1, sizeof(long long));
  long long * __restrict__ ONNX___tmp17 = (long long*) calloc(1, sizeof(long long));
  long long * __restrict__ ONNX___tmp18 = (long long*) calloc(1, sizeof(long long));
  long long * __restrict__ ONNX___tmp19 = (long long*) calloc(1, sizeof(long long));
  long long * __restrict__ ONNX___tmp2 = (long long*) calloc(3, sizeof(long long));
  long long * __restrict__ ONNX___tmp20 = (long long*) calloc(1, sizeof(long long));
  long long * __restrict__ ONNX___tmp21 = (long long*) calloc(1, sizeof(long long));
  long long * __restrict__ ONNX___tmp22 = (long long*) calloc(1, sizeof(long long));
  long long * __restrict__ ONNX___tmp23 = (long long*) calloc(1, sizeof(long long));
  long long * __restrict__ ONNX___tmp24 = (long long*) calloc(4, sizeof(long long));
  long long * __restrict__ ONNX___tmp25 = (long long*) calloc(4, sizeof(long long));
  long long * __restrict__ ONNX___tmp26 = (long long*) calloc(4, sizeof(long long));
  long long * __restrict__ ONNX___tmp27 = (long long*) calloc(3, sizeof(long long));
  long long * __restrict__ ONNX___tmp3 = (long long*) calloc(3, sizeof(long long));
  long long * __restrict__ ONNX___tmp4 = (long long*) calloc(3, sizeof(long long));
  long long * __restrict__ ONNX___tmp5 = (long long*) calloc(3, sizeof(long long));
  long long * __restrict__ ONNX___tmp6 = (long long*) calloc(4, sizeof(long long));
  long long * __restrict__ ONNX___tmp7 = (long long*) calloc(4, sizeof(long long));
  float * __restrict__ ONNX_attentionDOToutputDOTLayerNormDOTbias = (float*) calloc(768, sizeof(float));
  float * __restrict__ ONNX_attentionDOToutputDOTLayerNormDOTweight = (float*) calloc(768, sizeof(float));
  float * __restrict__ ONNX_attentionDOToutputDOTdenseDOTbias = (float*) calloc(768, sizeof(float));
  float * __restrict__ ONNX_attentionDOTselfDOTkeyDOTbias = (float*) calloc(768, sizeof(float));
  float * __restrict__ ONNX_attentionDOTselfDOTqueryDOTbias = (float*) calloc(768, sizeof(float));
  float * __restrict__ ONNX_attentionDOTselfDOTvalueDOTbias = (float*) calloc(768, sizeof(float));
  float * __restrict__ ONNX_inputDOT1 = (float*) calloc(3145728, sizeof(float));
  float * __restrict__ ONNX_intermediateDOTdenseDOTbias = (float*) calloc(3072, sizeof(float));
  float * __restrict__ ONNX_outputDOTLayerNormDOTbias = (float*) calloc(768, sizeof(float));
  float * __restrict__ ONNX_outputDOTLayerNormDOTweight = (float*) calloc(768, sizeof(float));
  float * __restrict__ ONNX_outputDOTdenseDOTbias = (float*) calloc(768, sizeof(float));

  __dace_init_dace_model(ONNX_133, ONNX_134, ONNX_135, ONNX_136, ONNX_137, ONNX_138, ONNX_139, ONNX_140, ONNX_141, ONNX_142, ONNX_143, ONNX_144, ONNX_146, ONNX_147, ONNX___tmp0, ONNX___tmp1, ONNX___tmp16, ONNX___tmp17, ONNX___tmp18, ONNX___tmp19, ONNX___tmp2, ONNX___tmp20, ONNX___tmp21, ONNX___tmp22, ONNX___tmp23, ONNX___tmp24, ONNX___tmp25, ONNX___tmp26, ONNX___tmp27, ONNX___tmp3, ONNX___tmp4, ONNX___tmp5, ONNX___tmp6, ONNX___tmp7, ONNX_attentionDOToutputDOTLayerNormDOTbias, ONNX_attentionDOToutputDOTLayerNormDOTweight, ONNX_attentionDOToutputDOTdenseDOTbias, ONNX_attentionDOTselfDOTkeyDOTbias, ONNX_attentionDOTselfDOTqueryDOTbias, ONNX_attentionDOTselfDOTvalueDOTbias, ONNX_inputDOT1, ONNX_intermediateDOTdenseDOTbias, ONNX_outputDOTLayerNormDOTbias, ONNX_outputDOTLayerNormDOTweight, ONNX_outputDOTdenseDOTbias, ONNX_100, ONNX_109, ONNX_112, ONNX_115, ONNX_128, ONNX_145, ONNX_148, ONNX_27, ONNX_30, ONNX_42, ONNX_45, ONNX_56, ONNX_59, ONNX_72, ONNX_78, ONNX_81, ONNX___tmp10, ONNX___tmp11, ONNX___tmp12, ONNX___tmp13, ONNX___tmp14, ONNX___tmp15, ONNX___tmp8, ONNX___tmp9);
  __program_dace_model(ONNX_133, ONNX_134, ONNX_135, ONNX_136, ONNX_137, ONNX_138, ONNX_139, ONNX_140, ONNX_141, ONNX_142, ONNX_143, ONNX_144, ONNX_146, ONNX_147, ONNX___tmp0, ONNX___tmp1, ONNX___tmp16, ONNX___tmp17, ONNX___tmp18, ONNX___tmp19, ONNX___tmp2, ONNX___tmp20, ONNX___tmp21, ONNX___tmp22, ONNX___tmp23, ONNX___tmp24, ONNX___tmp25, ONNX___tmp26, ONNX___tmp27, ONNX___tmp3, ONNX___tmp4, ONNX___tmp5, ONNX___tmp6, ONNX___tmp7, ONNX_attentionDOToutputDOTLayerNormDOTbias, ONNX_attentionDOToutputDOTLayerNormDOTweight, ONNX_attentionDOToutputDOTdenseDOTbias, ONNX_attentionDOTselfDOTkeyDOTbias, ONNX_attentionDOTselfDOTqueryDOTbias, ONNX_attentionDOTselfDOTvalueDOTbias, ONNX_inputDOT1, ONNX_intermediateDOTdenseDOTbias, ONNX_outputDOTLayerNormDOTbias, ONNX_outputDOTLayerNormDOTweight, ONNX_outputDOTdenseDOTbias, ONNX_100, ONNX_109, ONNX_112, ONNX_115, ONNX_128, ONNX_145, ONNX_148, ONNX_27, ONNX_30, ONNX_42, ONNX_45, ONNX_56, ONNX_59, ONNX_72, ONNX_78, ONNX_81, ONNX___tmp10, ONNX___tmp11, ONNX___tmp12, ONNX___tmp13, ONNX___tmp14, ONNX___tmp15, ONNX___tmp8, ONNX___tmp9);
  __dace_exit_dace_model(ONNX_133, ONNX_134, ONNX_135, ONNX_136, ONNX_137, ONNX_138, ONNX_139, ONNX_140, ONNX_141, ONNX_142, ONNX_143, ONNX_144, ONNX_146, ONNX_147, ONNX___tmp0, ONNX___tmp1, ONNX___tmp16, ONNX___tmp17, ONNX___tmp18, ONNX___tmp19, ONNX___tmp2, ONNX___tmp20, ONNX___tmp21, ONNX___tmp22, ONNX___tmp23, ONNX___tmp24, ONNX___tmp25, ONNX___tmp26, ONNX___tmp27, ONNX___tmp3, ONNX___tmp4, ONNX___tmp5, ONNX___tmp6, ONNX___tmp7, ONNX_attentionDOToutputDOTLayerNormDOTbias, ONNX_attentionDOToutputDOTLayerNormDOTweight, ONNX_attentionDOToutputDOTdenseDOTbias, ONNX_attentionDOTselfDOTkeyDOTbias, ONNX_attentionDOTselfDOTqueryDOTbias, ONNX_attentionDOTselfDOTvalueDOTbias, ONNX_inputDOT1, ONNX_intermediateDOTdenseDOTbias, ONNX_outputDOTLayerNormDOTbias, ONNX_outputDOTLayerNormDOTweight, ONNX_outputDOTdenseDOTbias, ONNX_100, ONNX_109, ONNX_112, ONNX_115, ONNX_128, ONNX_145, ONNX_148, ONNX_27, ONNX_30, ONNX_42, ONNX_45, ONNX_56, ONNX_59, ONNX_72, ONNX_78, ONNX_81, ONNX___tmp10, ONNX___tmp11, ONNX___tmp12, ONNX___tmp13, ONNX___tmp14, ONNX___tmp15, ONNX___tmp8, ONNX___tmp9);

  free(ONNX_133);
  free(ONNX_134);
  free(ONNX_135);
  free(ONNX_136);
  free(ONNX_137);
  free(ONNX_138);
  free(ONNX_139);
  free(ONNX_140);
  free(ONNX_141);
  free(ONNX_142);
  free(ONNX_143);
  free(ONNX_144);
  free(ONNX_146);
  free(ONNX_147);
  free(ONNX___tmp0);
  free(ONNX___tmp1);
  free(ONNX___tmp16);
  free(ONNX___tmp17);
  free(ONNX___tmp18);
  free(ONNX___tmp19);
  free(ONNX___tmp2);
  free(ONNX___tmp20);
  free(ONNX___tmp21);
  free(ONNX___tmp22);
  free(ONNX___tmp23);
  free(ONNX___tmp24);
  free(ONNX___tmp25);
  free(ONNX___tmp26);
  free(ONNX___tmp27);
  free(ONNX___tmp3);
  free(ONNX___tmp4);
  free(ONNX___tmp5);
  free(ONNX___tmp6);
  free(ONNX___tmp7);
  free(ONNX_attentionDOToutputDOTLayerNormDOTbias);
  free(ONNX_attentionDOToutputDOTLayerNormDOTweight);
  free(ONNX_attentionDOToutputDOTdenseDOTbias);
  free(ONNX_attentionDOTselfDOTkeyDOTbias);
  free(ONNX_attentionDOTselfDOTqueryDOTbias);
  free(ONNX_attentionDOTselfDOTvalueDOTbias);
  free(ONNX_inputDOT1);
  free(ONNX_intermediateDOTdenseDOTbias);
  free(ONNX_outputDOTLayerNormDOTbias);
  free(ONNX_outputDOTLayerNormDOTweight);
  free(ONNX_outputDOTdenseDOTbias);
  return 0;
}
