name: GPU CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-gpu:
    runs-on: [self-hosted, linux, gpu]
    env:
      ORT_ROOT: '/opt/onnxruntime'

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install dependencies
        env:
          UPDATE_PIP: 'true'
        run: |
          rm -rf .dacecache tests/.dacecache
          . /opt/setupenv
          make clean install


      - name: Install ORT
        run: |
          . venv/bin/activate
          cd /opt/onnxruntime
          ./build.sh --use_cuda --cuda_version=11.1 --cuda_home=/usr/local/cuda-11.1 --cudnn_home=/usr/local/cuda-11 --build_shared_lib --parallel --config Release


      - name: Test with pytest
        env:
          PYTEST_ARGS: --cov=daceml --cov-report=term --cov-report xml --cov-config=.coveragerc --gpu-only
        run: make test

      - name: Upload coverage
        run: make codecov
